name: Process Completed Translations

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'Languages/**'

jobs:
  validate-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Language Directories
        run: |
          mkdir -p Languages/en-US
          
      - name: Validate Translations
        run: |
          source_dir="Languages/en-US"
          # First check if any language directories exist besides en-US
          lang_dirs=$(find Languages -mindepth 1 -maxdepth 1 -type d ! -name 'en-US')
          
          if [ -z "$lang_dirs" ]; then
            echo "No translation directories found - this is okay for initial setup"
            exit 0
          fi
          
          for lang_dir in $lang_dirs; do
            # Check if all required files exist
            for source_file in $source_dir/*; do
              filename=$(basename "$source_file")
              trans_file="${lang_dir}/${filename}"
              
              if [ ! -f "$trans_file" ]; then
                echo "Missing file: $trans_file"
                exit 1
              fi
              
              # Validate based on file type
              if [[ $filename == *.json ]]; then
                # JSON validation
                if [ -f "$trans_file" ]; then
                  source_keys=$(jq 'keys | length' "$source_file")
                  trans_keys=$(jq 'keys | length' "$trans_file")
                  if [ "$source_keys" -ne "$trans_keys" ]; then
                    echo "Incomplete translation: $trans_file"
                    exit 1
                  fi
                fi
              elif [[ $filename == *.md ]]; then
                # Markdown validation - check if file has content
                if [ -f "$trans_file" ] && [ ! -s "$trans_file" ]; then
                  echo "Empty markdown file: $trans_file"
                  exit 1
                fi
              fi
            done
          done